name: Publish new release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Build release JSON blob
      run: python -m synapse.tools.genpkg --save synapse_triage.json synapse-triage.yaml

    # https://github.community/t/how-to-get-just-the-tag-name/16241/11
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    # https://github.com/marketplace/actions/publish-release

    - name: Create a new draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.SOURCE_TAG }}
        release_name: ${{ steps.get_tag.outputs.SOURCE_TAG }}
        draft: true
        prerelease: false
    
    - name: Upload package JSON blob to the release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./synapse_triage.json
        asset_name: synapse_triage.json
        asset_content_type: application/json
    
    - name: Publish release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}