name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run test suite
      run: python -m pytest test_synapse_triage.py
      env:
        SYNAPSE_TRIAGE_APIKEY: ${{ secrets.SYNAPSE_TRIAGE_APIKEY }}