name: Run Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        wget https://raw.githubusercontent.com/vertexproject/synapse/master/requirements.txt
        wget https://raw.githubusercontent.com/vertexproject/synapse/master/requirements_dev.txt
        python -m pip install -r requirements_dev.txt
    
    - name: Run test suite
      run: python -m pytest test_synapse_triage.py